apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: function-minio-event
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: limelapse.com/function-minio-event:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_MINIO_HOST
              value: "minio"
            - name: QUARKUS_MINIO_PORT
              value: "9000"
            - name: QUARKUS_MINIO_SECURE
              value: "false"
            - name: QUARKUS_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: ACCESS_KEY
            - name: QUARKUS_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: SECRET_KEY
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: function-minio-event-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/preserve-host: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: function-minio-event.limelapse.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: knative-bridge
                port:
                  number: 80
