apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: function-generate-preview
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: limelapse.com/function-generate-preview:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MINIO_IMAGES_BUCKET
              value: "images"
            - name: QUARKUS_REST_CLIENT_TIMELAPSEEXPORT_URL # uses the name of the k8s timelapse export service
              value: "http://timelapse-export:80"
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: "postgresql"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB # redundancy for next env var injection
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres:5432/$(POSTGRES_DB)"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: function-generate-preview-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/preserve-host: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $pass_access_scheme;
      proxy_set_header X-Forwarded-Port $pass_port;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - function-generate-preview.limelapse.com
      secretName: function-generate-preview-tls
  rules:
    - host: function-generate-preview.limelapse.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: knative-bridge
                port:
                  number: 80
