apiVersion: v1
kind: Service
metadata:
  name: kourier
  namespace: kourier-system
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: 3scale-kourier-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: knative-bridge
  namespace: default
spec:
  type: ExternalName
  externalName: kourier-internal.kourier-system.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80